### ISSUE TITLE
Starting video at a given position

### ISSUE THREAD

**Issue by gquemener** [dailymotion/dailymotion-sdk-js#19]
Hello,

Is it possible to start a video at a given position using `DM.player()`?
All I've succeeded to do right now is this:

``` javascript
var resumed = false;
var player = DM.player('player');
player.addEventListener('play', function() {
    if (!resumed) {
        player.seek(145.244);
        resumed = true;
    }
});
```

Is there any recommended way please?

**Comment by michaelvial** [comment]
Hi @gquemener,

Yes there is:
``` javascript
player = DM.player('player',{
  video: 'x2evjbi',
  params: {
    start: 10
  }
});
```

Will start video at 10s. See http://jsbin.com/nezaqunezi/1/edit?html,js,output

**Comment by gquemener** [comment]
I'm using the "DM Cloud" player sdk in fact (http://api.dmcloud.net/static/dmplayer/dmplayer-sdk.js),
I though it'd be the same API than for Dailymotion but the `start` params doesn't work.

**Comment by michaelvial** [comment]
So, after talking with the DmCloud team, this sdk is no more supported (As DmCloud is becoming Dailymotion Partner).
You should use the Dailymotion Js Sdk : https://github.com/dailymotion/dailymotion-sdk-js

It's the only true one :)

**Comment by gquemener** [comment]
I'm not sure the Dailymotion Partner will suit our need yet.

Maybe, we'll move to Dailymotion OpenVOD instead. Are they using the same js sdk too?

**Comment by MathildeS** [comment]
Hi, now, all dailymotion users will be using the same API and SDKs. 
indeed the link to SDK is https://github.com/dailymotion/dailymotion-sdk-js
and you'll find more info on the API at https://developer.dailymotion.com/

**Comment by gquemener** [comment]
Allright,

Thank you @michaelvial and @MathildeS :)
