### ISSUE TITLE
Set the player fullscreen

### ISSUE THREAD

**Issue by korasaccharin** [dailymotion/dailymotion-sdk-js#20]
Hello,

I wish to set fullscreen the player. But when I call `player.setFullscreen();`, this error is triggered:

```
Trying to call unimplemented API method: fullscreen
```

Others methods (play, pause, etc.) works well.

Thanks

**Comment by michaelvial** [comment]
Hi @korasaccharin,

This is not possible with the Flash player, the fullscreen mode can only be set by user input :
> Full-screen mode is initiated in response to a mouse click or key press by the user; the movie cannot change Stage.displayState without user input.
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Stage.html#displayState

However, `player.setFullscreen();` fully works on the Html5 player. You can init Dailymotion html5 player like this :

````javascript
player = DM.player('player',{
  video: 'x6q96t',
  width: '100%',
  height: '100%',
  params: {html: "1"}
});
```
