### ISSUE TITLE
Force html5 return on callback

### ISSUE THREAD

**Issue by tiagoleal25** [dailymotion/dailymotion-sdk-js#21]
Hi,

is it possible to force the callback to return html5 code instead of flash (swf) for example? And is it possible to force autoplay?

Best regards.

**Comment by MathildeS** [comment]
Hi, 

Already answered here: https://github.com/dailymotion/dailymotion-sdk-js/issues/25
Basically, our player already serves the most appropriate technology (flash or html5) depending on the context (mobile/desktop, vod/live, Flash player version, browser). For instance, our live streams are delivered in HLS only, not natively supported in chrome desktop. Hence it is not recommended to force the technology used by the player. 

About autoplay, you can have a look at the player documentation: https://developer.dailymotion.com/player We have an `autoplay` player parameter (https://developer.dailymotion.com/player#player-parameters) but note that this does not work on most mobile devices as those devices prevent videos from being played automatically (see [Apple documentation : Safari HTML5 Audio and Video Guide](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html#//apple_ref/doc/uid/TP40009523-CH5-SW1) for instance).

**Comment by refriedfood** [comment]
You totally did not answer the question, and no #25 answers nothing. dailymotion does not choose the appropriate player depending on the browser, unless by appropriate you mean "flash by default". You have to completely disable flash in order for your lousy site to even work on most versions of mozilla, even in opera it will use flash without displaying the video and only play the audio.
