### ISSUE TITLE
How may I hide the control handlebar by default ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [dailymotion/dailymotion-sdk-js#23]
Hi to everyone, I'm willing play in a third party player therefore I wonder how to hide the playbar ? 
Thx for tips.

**Comment by rymai** [comment]
Hello,

You can pass the `chromeless` parameter when initializing the player: https://developer.dailymotion.com/player#player-parameters

Example: http://jsfiddle.net/rg59veo7/2/

Hope that helps.

**Comment by be-next-hotdog** [comment]
Great, that does helps a lot, but I've simultaneously seen you changed the param from "chromless" to "controls" ? I retested with these 2 options, it works anyway.

**Comment by rymai** [comment]
Glad I could help. The current version of my comment is the correct one.
