### ISSUE TITLE
The property duration returns NaN ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [dailymotion/dailymotion-sdk-js#24]
As titile, the player's property returns value NaN so that I am neither able anymore to grab the video duration nor synchronize the time in seekbar ? 

What was wrong exactly ?

**Comment by Cycymomo** [comment]
you can gather information using:
```
window.addEventListener('apiready', () => {
  DM.api(
    `/video/${video.videoId}`,
    { fields: ['duration', 'description', 'title', 'thumbnail_url', 'updated_time', 'embed_url', 'owner', 'mode'] },
    result => {
      // result is an Object with all the fields wanted
      console.log('result', result)
    }
  )
})
```

sorry for the delay, we are cleaning issue of this old repo :)
