### ISSUE TITLE
Cant play live video on mode html 5

### ISSUE THREAD

**Issue by be-next-hotdog** [dailymotion/dailymotion-sdk-js#25]
The question is, we can play live video very well within a flash player, but doesn't run while switching to html5 mode (html: 1) ? 
Any learn & support tips ? Thx guys.

**Comment by xyfantis** [comment]
+1

**Comment by myarcane** [comment]
@be-next-hotdog : `html=1` parameter should only be used for testing purpose. The player already serves the most appropriate technology depending on the context (mobile/desktop, vod/live, Flash player version, browser). Our live streams are delivered in HLS only, not natively supported in chrome desktop. 

`html=1` will soon be removed from our official documentation.

**Comment by dharFr** [comment]
Closing as it's more a matter of player support than a real issue with the SDK.
