### ISSUE TITLE
Is there a proper way to destroy dailymotion player ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [dailymotion/dailymotion-sdk-js#26]
Ask as title.

**Comment by MyArcane** [comment]
For the moment our sdk doesn't implement a `destroy()` method but we will implement it soon. Thanks for the suggestion.

**Comment by danrossi** [comment]
I just ran into this problem for playlists with youtube. I believe you need to stop, and clear the iframe ? Youtube have a method called clearVideo

**Comment by VincentCharpentier** [comment]
Up, is these any progress on this topic ?
I'm looking for a proper way to clear listeners and revert the DOM to it's original state

Thank you

**Comment by Cycymomo** [comment]
hey ! Finally done in https://github.com/dailymotion/dailymotion-sdk-js/pull/72
