### ISSUE TITLE
Error prevents ad and content from playing

### ISSUE THREAD

**Issue by denisvlr** [dailymotion/dailymotion-sdk-js#40]
I ran into issues on the iframe embedded player, sometimes it fails to load with the following error:
```
Uncaught (in promise) TypeError: Cannot read property 'reject' of null
at Function.t (http://static1.dmcdn.net/playerv5/6a37145342d12c8316f4.dmp.js:6:20417)
at http://static1.dmcdn.net/playerv5/6a37145342d12c8316f4.dmp.js:3:18161
at Array.forEach (native)
at i.t (http://static1.dmcdn.net/playerv5/6a37145342d12c8316f4.dmp.js:3:18102)
at i.t (http://static1.dmcdn.net/playerv5/6a37145342d12c8316f4.dmp.js:6:15945)
at http://static1.dmcdn.net/playerv5/6a37145342d12c8316f4.dmp.js:6:15264
```
The video then freezes on the spinner, preventing any ad or video to display.

Any idea why this happens?

(NB: also posted this on stackoverflow: http://stackoverflow.com/questions/42391173/dailymotion-player-error-prevents-ad-and-content-from-playing)

**Comment by michaelvial** [comment]
Hi @denisvlr. Do you have a link where I can see the issue?
