### ISSUE TITLE
Crash under firefox / ubuntu

### ISSUE THREAD

**Issue by JSteunou** [dailymotion/dailymotion-sdk-js#48]
Ubuntu 17.04  - Firefox 55

![capture du 2017-09-26 11-20-05](https://user-images.githubusercontent.com/2323127/30867907-866d0386-a2dd-11e7-857f-bf76809bff46.png)

You can see the original issue here https://github.com/mediaelement/mediaelement/issues/2409

**Comment by dharFr** [comment]
Hello @JSteunou 

Thanks for the feedback. 

Unfortunately, I was not able to reproduce from here. Could you please provide a test case? Like a [jsfiddle.net](https://jsfiddle.net/) or [jsbin.com](http://jsbin.com/)?
Thanks

**Comment by JSteunou** [comment]
@dharFr not had the time for a fiddle, but real live example https://www.gamekult.com/jeux/days-gone-3050714987/video-3052047435.html#player

**Comment by dharFr** [comment]
I can't reproduce on gamekult either 😞. Maybe it's ubuntu specfic

**Comment by JSteunou** [comment]
no problem, thanks to looking at it. With an Ubuntu VM you might reproduce it if you do not have any Ubuntu PC.
