### ISSUE TITLE
Problem with mixed security on Chrome

### ISSUE THREAD

**Issue by machunter** [dailymotion/dailymotion-sdk-js#5]
Chrome by default (recently?) seems to block mixed secure content. 

I am have started getting the following error: 

```
[blocked] The page at 'https://xxxxx/yyy' was loaded over HTTPS, but ran insecure content from 'http://www.dailymotion.com/embed/video/x10t7bf?api=postMessage&id=dmwidget': this content should also be loaded over HTTPS.
```

is there an option to force loading from https instead of http?

(note the SDK is loaded of https)

**Comment by leonardop21** [comment]
Solved. Thanks @dharFr
