### ISSUE TITLE
Dailymotion for video.js 5.0 

### ISSUE THREAD

**Issue by onigetoc** [dailymotion/dailymotion-sdk-js#52]
Hi, 
I need help and contributors to create a working version for video.js 5.0+
This is a very basic version

I started a new project here:
https://github.com/onigetoc/videojs-5.0-dailymotion

Online demo: https://plnkr.co/edit/s6Ql4I324cYioADy9CPS?p=preview

**Comment by mccarthypaulmichael** [comment]
HI @onigetoc, thanks for the message. As this isn't an issue relating to our SDK I'm going to close it out for now and we invite you to contact our support team if any help is required.
