### ISSUE TITLE
Qualities is returning empty for all videos

### ISSUE THREAD

**Issue by danrossi** [dailymotion/dailymotion-sdk-js#57]
This seems to be a recent bug. All videos is returning an empty qualities properly. I can confirm with the github build also

```
{event: "qualitiesavailable", id: "dm739965400996", qualities: {…}}
event
:
"qualitiesavailable"
id
:
"dm739965400996"
qualities
:
__proto__
:
constructor
:
ƒ Object()
hasOwnProperty
:
ƒ hasOwnProperty()
isPrototypeOf
:
ƒ isPrototypeOf()
propertyIsEnumerable
:
ƒ propertyIsEnumerable()
toLocaleString
:
ƒ toLocaleString()
toString
:
ƒ toString()
valueOf
:
ƒ valueOf()
__defineGetter__
:
ƒ __defineGetter__()
__defineSetter__
:
ƒ __defineSetter__()
__lookupGetter__
:
ƒ __lookupGetter__()
__lookupSetter__
:
ƒ __lookupSetter__()
get __proto__
:
ƒ __proto__()
set __proto__
:
ƒ __proto__()
arguments
:
(...)
caller
:
(...)
length
:
1
name
:
"set __proto__"
__proto__
:
ƒ ()
[[Scopes]]
:
Scopes
```

Any ideas ?

**Comment by danrossi** [comment]
Any ideas if this issue has been fixed ? It seems to be broken.

**Comment by danrossi** [comment]
I believe the whole qualities event thing is broken. And the available qualities is required to be loaded from the metadata ie

https://www.dailymotion.com/player/metadata/video/x36xhzz

**Comment by danrossi** [comment]
Fiddle https://jsfiddle.net/danrossi303/4t0n6xms/3/

**Comment by dmail** [comment]
We're working on it, thank you very much for the fiddle :)

**Comment by danrossi** [comment]
@dmail Thanks for that. Do I need to work with that pr branch and build instead of using the all.js file then ?

**Comment by dmail** [comment]
@danrossi We are reviewing and testing the branch to ensure it works well. Once it's done it will be merged to master and `all.js` hosted on the CDN will be updated. It should happen next week.

If you're in a hurry, you can temporarily use the branch to build your own `all.js`.

**Comment by danrossi** [comment]
Confirmed that branch is working I have to load it internally for now.

**Comment by dmail** [comment]
https://github.com/dailymotion/dailymotion-sdk-js/pull/58 has been merged and http://api.dmcdn.net/all.js was updated approximatively 6 hours ago.
For you information this file is cached for 12hours so you have to invalid your browser cache or wait 6 hours to get the new `all.js` file.

Let us know if you have any trouble.
