### ISSUE TITLE
Was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint

### ISSUE THREAD

**Issue by leonardop21** [dailymotion/dailymotion-sdk-js#62]
I'm trying to upload videos through my site configured with https and using sdk in javascript, however, I get an error stating that the endpoint is not secure.

was loaded by HTTPS, but requested an unsafe XMLHttpRequest endpoint

I did the test on an unsecured connection (http) and the upload occurred without any problems, however, the production site, all the traffic is encrypted, and the dailymotion endpoint is http. How could you solve this problem?

**Comment by jakub-g** [comment]
Hello @leonardop21 could you provide sample code to repro your issue?

**Comment by SuperToma** [comment]
As @dharFr replied : use `ssl_assets` in url /file/upload

`DM.api('/file/upload?ssl_assets',` ...

cf. https://github.com/dailymotion/dailymotion-sdk-js/issues/5#issuecomment-425888913

Regards,

**Comment by leonardop21** [comment]
It worked, thanks for the help @SuperToma 

Could you add that to the documentation please!
