### ISSUE TITLE
How to hide debug console messages?

### ISSUE THREAD

**Issue by adeeb1** [dailymotion/dailymotion-sdk-js#63]
When I load a Dailymotion player on my website, it displays debug logs for everything that it does. Is there a way to turn off these debug logs?

![dailymotion_debug_logs](https://user-images.githubusercontent.com/4312320/50048211-fb155480-007a-11e9-8a19-e2ee7daf1c49.jpg)

**Comment by nicoferron** [comment]
Hello @adeeb1 ,

Thank you for reporting the issue.
We will push a fix in the following days allowing you to turn off those extra debug messages by using the `logging: false` parameter in your `DM.init();`

Regards,

**Comment by nicoferron** [comment]
Hello @adeeb1 ,

We fixed the Debug lines displayed in the console. The timestamps lines will be fixed in a second time.

Regards,

**Comment by adeeb1** [comment]
Hi @nicoferron, awesome! Thank you very much!

**Comment by nicoferron** [comment]
Hello @adeeb1, I made a mistake. In fact you don't need to use the `logging` parameter to remove the debug logs. We removed them anyway

**Comment by 1cgonza** [comment]
Hi @nicoferron, don't know if you are still working on this but I am also using the `DM.player` and would like to remove de logs. You mentioned before that they had been removed but I still get them. Tried the `logging` parameter but nothing changed. Is there a new way of removing them? 
Thanks in advance!

**Comment by jakub-g** [comment]
Hello, the issue about the first two logs doesn't come from the SDK but directly from the Dailymotion player. We're working on fixing that.
