### ISSUE TITLE
types?

### ISSUE THREAD

**Issue by is2ei** [dailymotion/dailymotion-sdk-js#78]
It would be nice to have types for this SDK officially. 😃 
Is there any plan for that?

**Comment by mccarthypaulmichael** [comment]
Hi @is2ei thanks for the mail, can you please explain in more detail what exactly you are looking for?

**Comment by DionoCorbelWebedia** [comment]
Hi! I think @is2ei is talking about @types for typescript.
If we use the "DM" global variable with  typescript, we miss the type declarations.
it would be helpful if you could add a @types/dailymotion package just for type declarations... right @is2ei?

**Comment by mccarthypaulmichael** [comment]
Hi @DionoCorbelWebedia & @is2ei, thanks for the messages. 

Firstly I'd like to highlight we are in the process of discontinuing support for this SDK. We've released a newer more advanced SDK and we invite you to check out the documentation at https://developer.dailymotion.com/player/#embed-website. 

Regarding the above question on types, this isn't something we support at the moment with either SDK, but we may review this in the future and will let you know if we plan to have this officially. Thanks again.

**Comment by DionoCorbelWebedia** [comment]
If it helps in the future.
Here we have the documentation to add the type declaration: 😃
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by Cycymomo** [comment]
hey 👋 closing this issue as we deprecate this integration method.
We no longer support this SDK for Player integration. It can be used for interaction with the Data API only.
The Player should be embedded using the new default Player integration method, info can be found [here](https://developer.dailymotion.com/player/#embed-website).
