### ISSUE TITLE
The player cannot be in full screen.

### ISSUE THREAD

**Issue by kyky1314** [dailymotion/dailymotion-sdk-js#92]
When the browser is changed to the mobile phone mode, the player is not displayed in full screen mode.

![image](https://user-images.githubusercontent.com/21274105/110724118-25511f00-8250-11eb-851d-57f5fd9a95c9.png)

**Comment by johansatge** [comment]
Hello @sm0-1314,

could you please specify the steps you are following, and the expected result?

When trying myself on the SDK test page (see example below), the fullscreen feature seems to be working as expected.

Thank you!

https://user-images.githubusercontent.com/5699295/111640310-5e633380-87fc-11eb-91a9-096f1f8deed8.mp4
